name: simple_notifier
description: A simple extension to simplify ValueNotifier usage for Flutter applications.
version: 1.0.6
homepage: https://kakzaki.dev
repository: https://github.com/kakzaki/simple_notifier.git

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

